apiVersion: apps/v1
kind: Deployment
metadata:
  name: storeserviceat
  labels:
    app: storeserviceat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storeserviceat
  template:
    metadata:
      labels:
        app: storeserviceat
    spec:
      containers:
      - name: storeserviceat
        image: natanborrges/storeserviceat:latest
        ports:
        - containerPort: 7001
        env:
          - name: AMQP_HOSTNAME
            value: rabbitmq
          - name: RABBIT_PORT
            value: "5672"
          - name: AMQP_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbit-user
                key: username
          - name: AMQP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbit-user
                key: password

